// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Models;

public partial class Litigios
{
    public int id_Ltg { get; set; }

    public string ltg_acto { get; set; }

    public DateTime ltg_fecha { get; set; }

    public int? id_sentencia { get; set; }

    public int id_Estatus { get; set; }

    public DateTime? ltg_fecha_litigio { get; set; }
}