// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2.Server.Models;

public partial class LogActividad
{
    public int idLog { get; set; }

    public string URL { get; set; }

    public int idUsuario { get; set; }

    public string Metodo { get; set; }

    public DateTime Fecha { get; set; }

    public string Data { get; set; }
}