// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Models;

public partial class Logins
{
    public string LogginUsuario { get; set; }

    public int IdUsuario { get; set; }

    public DateTime? FechaHora { get; set; }

    public string Contraseña { get; set; }

    public virtual Usuarios IdUsuarioNavigation { get; set; }

    public virtual ICollection<Usuarios> Usuarios { get; set; } = new List<Usuarios>();
}