// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2.Server.Models;

public partial class perfilesVistas
{
    public int idPerfilVista { get; set; }

    public int idPerfil { get; set; }

    public int idVista { get; set; }
}