// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2.Server.Models;

public partial class Perfiles
{
    public int idPerfil { get; set; }

    public string nombre { get; set; }
    public object Nombre { get; internal set; }
    public string Descripcion { get; set; }

    public bool? porDefecto { get; set; }
    public bool PorDefecto { get; internal set; }
}