// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2.Server.Models;

public partial class t_ruta_archivos
{
    public int rua_id { get; set; }

    public string rua_descripcion { get; set; }

    public string rua_ruta { get; set; }

    public string rua_usuario { get; set; }

    public string rua_contrasena { get; set; }

    public int? est_id { get; set; }
}