// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2.Server.Models;

public partial class Tipo_Sentencia
{
    public int id_Sentencia { get; set; }

    public string desc_Sentencia { get; set; }
}