// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Models;

public partial class TRutaArchivos
{
    public int RuaId { get; set; }

    public string RuaDescripcion { get; set; }

    public string RuaRuta { get; set; }

    public string RuaUsuario { get; set; }

    public string RuaContrasena { get; set; }

    public int? EstId { get; set; }
}