// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Models;

public partial class Usuarios
{
    public int IdUsuario { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int IdPerfil { get; set; }

    public bool Activo { get; set; }

    public string IdLoggin { get; set; }

    public virtual Logins IdLogginNavigation { get; set; }

    public virtual ICollection<Logins> Logins { get; set; } = new List<Logins>();
}