// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2.Server.Models;

public partial class Usuarios
{
    public int idUsuario { get; set; }

    public string nombres { get; set; }
    public string Nombres { get; internal set; }
    public string apellidos { get; set; }
    public string Apellidos { get; internal set; }
    public DateTime fechaCreacion { get; set; }

    public int idPerfil { get; set; }

    public string usuario { get; set; }
    public string Usuario { get; internal set; }
    public bool Activo { get; set; }
    public DateTime FechaCrea { get; internal set; }
}