// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2.Server.Models;

public partial class Usuarios
{
    public int idUsuario { get; set; }

    public int? idPerfil { get; set; }

    public string Usuario { get; set; }

    public DateTime FechaCrea { get; set; }

    public bool Activo { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }
}