// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Audiencias
{
    public int Id_audiencia { get; set; }

    public int Id_litigio { get; set; }

    public int? Id_tribunal { get; set; }

    public string Numero { get; set; }

    public string Tipo { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual ICollection<Evidencias> Evidencias { get; set; } = new List<Evidencias>();

    public virtual Litigios Id_litigioNavigation { get; set; }

    public virtual Tribunales Id_tribunalNavigation { get; set; }
}
public partial class Audienciasltg
{

    public int Id_audiencia { get; set; }
    public int Id_litigio { get; set; }

    public string Numero { get; set; }

    public string Tipo { get; set; }
    public DateTime? Fecha { get; set; }

    public virtual ICollection<Evidencias> Evidencias { get; set; } = new List<Evidencias>();


}


    public class AudienciaCalendarioDto
    {
        public int Id_audiencia { get; set; }
        public string NumeroAudiencia { get; set; }
        public string TipoAudiencia { get; set; }
        public DateTime FechaAudiencia { get; set; }

        public int? IdSala { get; set; }
        public string NombreSala { get; set; }

        public int? Id_Tribunal { get; set; }
        public string Nombre_Tribunal { get; set; }

        public int? id_Ltg { get; set; }
        public string ltg_acto { get; set; }
        public string ltg_Nombre_Demandante { get; set; }

        public int? id_demanda { get; set; }
        public string TipoDemanda { get; set; }
    }




