// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Audiencias
{
    public int Id_audiencia { get; set; }

    public int Id_litigio { get; set; }

    public int? Id_tribunal { get; set; }

    public string Numero { get; set; }

    public string Tipo { get; set; }

    public DateTime? Fecha { get; set; }

    public string Sala { get; set; }

    public virtual ICollection<Evidencias> Evidencias { get; set; } = new List<Evidencias>();

    public virtual Litigios Id_litigioNavigation { get; set; }

    public virtual Tribunales Id_tribunalNavigation { get; set; }
}