// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Estatus_Litigios
{
    public int ltg_estatus { get; set; }

    public string ltg_description { get; set; }

    public virtual ICollection<Litigios> Litigios { get; set; } = new List<Litigios>();
}