// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Evidencias
{
    public int Id_Evidencia { get; set; }

    public int Id_audiencia { get; set; }

    public int id_usuario { get; set; }

    public string Nombre_Evidencia { get; set; }

    public string Ruta_Archivo { get; set; }

    public string Nombre_Archivo { get; set; }

    public string Comentario_Evidencia { get; set; }

    public DateTime Fecha { get; set; }
}