// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Historico_Litigio
{
    public int Id_historial { get; set; }

    public int Id_litigio { get; set; }

    public string Tipo_cambio { get; set; }

    public string Valor_anterior { get; set; }

    public string Valor_nuevo { get; set; }

    public DateTime? Fecha_cambio { get; set; }

    public string Observacion { get; set; }

    public int? Usuario_id { get; set; }

    public virtual Litigios Id_litigioNavigation { get; set; }
}