// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Litigios
{
    public int id_Ltg { get; set; }

    public string ltg_acto { get; set; }

    public DateTime ltg_Fecha_Acto { get; set; }

    public int id_Tipo_Demanda { get; set; }

    public string ltg_Cedula_Demandante { get; set; }

    public string ltg_Nacionalidad { get; set; }

    public string ltg_Demandante { get; set; }

    public string ltg_Tipo_Demandante { get; set; }

    public string ltg_Cedula_Representante { get; set; }

    public string ltg_Nombre_Representante { get; set; }

    public DateTime? ltg_Fecha_Audiencia { get; set; }

    public DateTime? ltg_Fecha_Actualizacion { get; set; }

    public int? id_Tribunal { get; set; }

    public int? id_Sentencia { get; set; }

    public int id_usuario { get; set; }

    public int? id_ruta { get; set; }

    public int id_Estatus { get; set; }

    public virtual Estatus_Litigios id_EstatusNavigation { get; set; }

    public virtual Tipo_Sentencia id_SentenciaNavigation { get; set; }

    public virtual Tipo_Demanda id_Tipo_DemandaNavigation { get; set; }

    public virtual Tribunales id_TribunalNavigation { get; set; }

    public virtual Ruta_archivos id_rutaNavigation { get; set; }

    public virtual Usuarios id_usuarioNavigation { get; set; }
}