// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Models;

public partial class Litigios
{
    public int IdLtg { get; set; }

    public string LtgActo { get; set; }

    public DateTime LtgFecha { get; set; }

    public int? IdSentencia { get; set; }

    public int IdEstatus { get; set; }

    public DateTime? LtgFechaLitigio { get; set; }

    public string DocDemandante { get; set; }

    public string Ltg { get; set; }
}