// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class LogError
{
    public int idLogError { get; set; }

    public int idUsuario { get; set; }

    public DateTime Fecha { get; set; }

    public string Mensaje { get; set; }

    public string StackTrace { get; set; }

    public string Origen { get; set; }

    public string Tipo { get; set; }
}