// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Models;

public partial class PerfilesVistas
{
    public int IdPerfilVista { get; set; }

    public int IdPerfil { get; set; }

    public int IdVista { get; set; }
}