// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Models;

public partial class Perfiles
{
    public int IdPerfil { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public bool? PorDefecto { get; set; }
}