// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Ruta_archivos
{
    public int id_Ruta { get; set; }

    public string Ruta { get; set; }

    public string Nombre { get; set; }

    public int id_usuario { get; set; }

    //public IFormFile Archivo { get; set; }

    public virtual ICollection<Litigios> Litigios { get; set; } = new List<Litigios>();
}