// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using static Dapper.SqlMapper;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Ruta_archivos
{
    public int id_Ruta { get; set; }

    public string Ruta { get; set; }
       

    public DateTime? fecha { get; set; }
    public string Ruta_Nombre { get; set; }

    public int id_usuario { get; set; }
    public int id_litigio { get; set; }

    // Propiedad de navegación
    [ForeignKey("id_litigio")]
    public ICollection<Litigios> Litigios { get; set; }

}