// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Salas
{
    public int IdSala { get; set; }

    public string Nombre { get; set; }

    public int IdTribunal { get; set; }

    public virtual Tribunales IdTribunalNavigation { get; set; }
}