// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Tipo_Demanda
{
    public int id_demanda { get; set; }

    public string Nombre { get; set; }

    public int id_Estatus { get; set; }

    public virtual ICollection<Litigios> Litigios { get; set; } = new List<Litigios>();
}