// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Tribunales
{
    public int Id_Tribunal { get; set; }

    public string Nombre_Tribunal { get; set; }

    public string Descripcion { get; set; }

    public string Telefono { get; set; }

    public decimal? Latitud { get; set; }

    public decimal? Longitud { get; set; }

    public int IdEstatus { get; set; }

    public string Direccion { get; set; }

    public virtual ICollection<Litigios> Litigios { get; set; } = new List<Litigios>();
}