// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;

namespace Sistema_Legal_2._0.Server.Entities;

public partial class Usuarios
{
    public int idUsuario { get; set; }

    public string nombres { get; set; }

    public string apellidos { get; set; }

    public DateTime fechaCreacion { get; set; }

    public int idPerfil { get; set; }

    public bool Activo { get; set; }

    public string nombreUsuario { get; set; }
    public string Email { get; set; }

    public int? idSupervisor { get; set; }

    public virtual ICollection<Audiencias> Audiencias { get; set; } = new List<Audiencias>();

    public virtual ICollection<Litigios> Litigios { get; set; } = new List<Litigios>();

    public virtual Perfiles idPerfilNavigation { get; set; }

    public virtual ICollection<Litigios> id_Ltg { get; set; } = new List<Litigios>();
}